FROM node:18.20-slim

WORKDIR /usr/local/app

COPY package*.json ./

RUN npm ci

RUN npm install -g @angular/cli@16.2.6

COPY . ./

EXPOSE 4200

CMD ng serve --host 0.0.0.0 --poll 2000 --configuration=hmr --proxy-config ./src/proxy.conf.json